var searchData=
[
  ['samesizetupleprefixcomparator',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['satcasthelper',['SatCastHelper',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1SatCastHelper.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_201_2c_20vecd_20_3e',['SatCastHelper&lt; 1, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1SatCastHelper_3_011_00_01VecD_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_202_2c_20vecd_20_3e',['SatCastHelper&lt; 2, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1SatCastHelper_3_012_00_01VecD_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_203_2c_20vecd_20_3e',['SatCastHelper&lt; 3, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1SatCastHelper_3_013_00_01VecD_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['satcasthelper_3c_204_2c_20vecd_20_3e',['SatCastHelper&lt; 4, VecD &gt;',['../structcv_1_1gpu_1_1device_1_1vec__math__detail_1_1SatCastHelper_3_014_00_01VecD_01_4.html',1,'cv::gpu::device::vec_math_detail']]],
  ['saturate_5fcast_5ffunc',['saturate_cast_func',['../structcv_1_1gpu_1_1device_1_1saturate__cast__func.html',1,'cv::gpu::device']]],
  ['savedindexparams',['SavedIndexParams',['../structcvflann_1_1SavedIndexParams.html',1,'cvflann']]],
  ['scan_5fcontext',['scan_context',['../structscan__context.html',1,'']]],
  ['scoped_5fptr',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20t_20_3e',['scoped_ptr&lt; const T &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3aparamiteratorinterface_3c_20t_20_3e_20_3e',['scoped_ptr&lt; testing::internal::ParamIteratorInterface&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3atestmetafactorybase_3c_20paramtype_20_3e_20_3e',['scoped_ptr&lt; testing::internal::TestMetaFactoryBase&lt; ParamType &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedtrace',['ScopedTrace',['../classtesting_1_1internal_1_1ScopedTrace.html',1,'testing::internal']]],
  ['seamfinder',['SeamFinder',['../classcv_1_1detail_1_1SeamFinder.html',1,'cv::detail']]],
  ['searchparams',['SearchParams',['../structcvflann_1_1SearchParams.html',1,'cvflann']]],
  ['select',['Select',['../structcv_1_1gpu_1_1device_1_1type__traits__detail_1_1Select.html',1,'cv::gpu::device::type_traits_detail']]],
  ['select_3c_20false_2c_20t1_2c_20t2_20_3e',['Select&lt; false, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1type__traits__detail_1_1Select_3_01false_00_01T1_00_01T2_01_4.html',1,'cv::gpu::device::type_traits_detail']]],
  ['setting',['Setting',['../classlibconfig_1_1Setting.html',1,'libconfig']]],
  ['settingexception',['SettingException',['../classlibconfig_1_1SettingException.html',1,'libconfig']]],
  ['settingnameexception',['SettingNameException',['../classlibconfig_1_1SettingNameException.html',1,'libconfig']]],
  ['settingnotfoundexception',['SettingNotFoundException',['../classlibconfig_1_1SettingNotFoundException.html',1,'libconfig']]],
  ['settings',['Settings',['../classtld_1_1Settings.html',1,'tld']]],
  ['settingtypeexception',['SettingTypeException',['../classlibconfig_1_1SettingTypeException.html',1,'libconfig']]],
  ['shiftdispatcher',['ShiftDispatcher',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1ShiftDispatcher.html',1,'cv::gpu::device::functional_detail']]],
  ['shiftdispatcher_3c_20func_2c_20false_20_3e',['ShiftDispatcher&lt; Func, false &gt;',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1ShiftDispatcher_3_01Func_00_01false_01_4.html',1,'cv::gpu::device::functional_detail']]],
  ['shiftdispatcher_3c_20func_2c_20true_20_3e',['ShiftDispatcher&lt; Func, true &gt;',['../structcv_1_1gpu_1_1device_1_1functional__detail_1_1ShiftDispatcher_3_01Func_00_01true_01_4.html',1,'cv::gpu::device::functional_detail']]],
  ['singlemask',['SingleMask',['../structcv_1_1gpu_1_1device_1_1SingleMask.html',1,'cv::gpu::device']]],
  ['singlemaskchannels',['SingleMaskChannels',['../structcv_1_1gpu_1_1device_1_1SingleMaskChannels.html',1,'cv::gpu::device']]],
  ['small_5fany_5fpolicy',['small_any_policy',['../structcvflann_1_1anyimpl_1_1small__any__policy.html',1,'cvflann::anyimpl']]],
  ['smem',['smem',['../structcv_1_1gpu_1_1device_1_1Emulation_1_1smem.html',1,'cv::gpu::device::Emulation']]],
  ['sparsepyrlkoptflowestimator',['SparsePyrLkOptFlowEstimator',['../classcv_1_1videostab_1_1SparsePyrLkOptFlowEstimator.html',1,'cv::videostab']]],
  ['sphericalportraitprojector',['SphericalPortraitProjector',['../structcv_1_1detail_1_1SphericalPortraitProjector.html',1,'cv::detail']]],
  ['sphericalportraitwarper',['SphericalPortraitWarper',['../classcv_1_1detail_1_1SphericalPortraitWarper.html',1,'cv::detail']]],
  ['sphericalprojector',['SphericalProjector',['../structcv_1_1detail_1_1SphericalProjector.html',1,'cv::detail']]],
  ['sphericalwarper',['SphericalWarper',['../classcv_1_1SphericalWarper.html',1,'cv']]],
  ['sphericalwarper',['SphericalWarper',['../classcv_1_1detail_1_1SphericalWarper.html',1,'cv::detail']]],
  ['stabilizerbase',['StabilizerBase',['../classcv_1_1videostab_1_1StabilizerBase.html',1,'cv::videostab']]],
  ['startstoptimer',['StartStopTimer',['../classcvflann_1_1StartStopTimer.html',1,'cvflann']]],
  ['static',['Static',['../structcv_1_1gpu_1_1device_1_1Static.html',1,'cv::gpu::device']]],
  ['static_3c_20true_20_3e',['Static&lt; true &gt;',['../structcv_1_1gpu_1_1device_1_1Static_3_01true_01_4.html',1,'cv::gpu::device']]],
  ['staticasserttypeeqhelper',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper_3_01T_00_01T_01_4.html',1,'testing::internal']]],
  ['staticif',['StaticIf',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1StaticIf.html',1,'cv::gpu::device::reduce_detail']]],
  ['staticif',['StaticIf',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1StaticIf.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['staticif_3c_20false_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; false, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1StaticIf_3_01false_00_01T1_00_01T2_01_4.html',1,'cv::gpu::device::reduce_detail']]],
  ['staticif_3c_20false_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; false, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1StaticIf_3_01false_00_01T1_00_01T2_01_4.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['staticif_3c_20true_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; true, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__detail_1_1StaticIf_3_01true_00_01T1_00_01T2_01_4.html',1,'cv::gpu::device::reduce_detail']]],
  ['staticif_3c_20true_2c_20t1_2c_20t2_20_3e',['StaticIf&lt; true, T1, T2 &gt;',['../structcv_1_1gpu_1_1device_1_1reduce__key__val__detail_1_1StaticIf_3_01true_00_01T1_00_01T2_01_4.html',1,'cv::gpu::device::reduce_key_val_detail']]],
  ['stereobeliefpropagation',['StereoBeliefPropagation',['../classcv_1_1gpu_1_1StereoBeliefPropagation.html',1,'cv::gpu']]],
  ['stereobeliefpropagation',['StereoBeliefPropagation',['../classcv_1_1ocl_1_1StereoBeliefPropagation.html',1,'cv::ocl']]],
  ['stereobm_5fgpu',['StereoBM_GPU',['../classcv_1_1gpu_1_1StereoBM__GPU.html',1,'cv::gpu']]],
  ['stereobm_5focl',['StereoBM_OCL',['../classcv_1_1ocl_1_1StereoBM__OCL.html',1,'cv::ocl']]],
  ['stereoconstantspacebp',['StereoConstantSpaceBP',['../classcv_1_1ocl_1_1StereoConstantSpaceBP.html',1,'cv::ocl']]],
  ['stereoconstantspacebp',['StereoConstantSpaceBP',['../classcv_1_1gpu_1_1StereoConstantSpaceBP.html',1,'cv::gpu']]],
  ['stereographicprojector',['StereographicProjector',['../structcv_1_1detail_1_1StereographicProjector.html',1,'cv::detail']]],
  ['stereographicwarper',['StereographicWarper',['../classcv_1_1StereographicWarper.html',1,'cv']]],
  ['stereographicwarper',['StereographicWarper',['../classcv_1_1detail_1_1StereographicWarper.html',1,'cv::detail']]],
  ['stitcher',['Stitcher',['../classcv_1_1Stitcher.html',1,'cv']]],
  ['strbuf_5ft',['strbuf_t',['../structstrbuf__t.html',1,'']]],
  ['stream',['Stream',['../classcv_1_1gpu_1_1Stream.html',1,'cv::gpu']]],
  ['streamaccessor',['StreamAccessor',['../structcv_1_1gpu_1_1StreamAccessor.html',1,'cv::gpu']]],
  ['string',['String',['../classtesting_1_1internal_1_1String.html',1,'testing::internal']]],
  ['superresolution',['SuperResolution',['../classcv_1_1superres_1_1SuperResolution.html',1,'cv::superres']]],
  ['surf_5focl',['SURF_OCL',['../classcv_1_1ocl_1_1SURF__OCL.html',1,'cv::ocl']]],
  ['surffeaturesfinder',['SurfFeaturesFinder',['../classcv_1_1detail_1_1SurfFeaturesFinder.html',1,'cv::detail']]]
];
