var searchData=
[
  ['pairwiseseamfinder',['PairwiseSeamFinder',['../classcv_1_1detail_1_1PairwiseSeamFinder.html',1,'cv::detail']]],
  ['paniniportraitprojector',['PaniniPortraitProjector',['../structcv_1_1detail_1_1PaniniPortraitProjector.html',1,'cv::detail']]],
  ['paniniportraitwarper',['PaniniPortraitWarper',['../classcv_1_1PaniniPortraitWarper.html',1,'cv']]],
  ['paniniportraitwarper',['PaniniPortraitWarper',['../classcv_1_1detail_1_1PaniniPortraitWarper.html',1,'cv::detail']]],
  ['paniniprojector',['PaniniProjector',['../structcv_1_1detail_1_1PaniniProjector.html',1,'cv::detail']]],
  ['paniniwarper',['PaniniWarper',['../classcv_1_1detail_1_1PaniniWarper.html',1,'cv::detail']]],
  ['paniniwarper',['PaniniWarper',['../classcv_1_1PaniniWarper.html',1,'cv']]],
  ['parameterizedtestcaseinfo',['ParameterizedTestCaseInfo',['../classtesting_1_1internal_1_1ParameterizedTestCaseInfo.html',1,'testing::internal']]],
  ['parameterizedtestcaseinfobase',['ParameterizedTestCaseInfoBase',['../classtesting_1_1internal_1_1ParameterizedTestCaseInfoBase.html',1,'testing::internal']]],
  ['parameterizedtestcaseregistry',['ParameterizedTestCaseRegistry',['../classtesting_1_1internal_1_1ParameterizedTestCaseRegistry.html',1,'testing::internal']]],
  ['parameterizedtestfactory',['ParameterizedTestFactory',['../classtesting_1_1internal_1_1ParameterizedTestFactory.html',1,'testing::internal']]],
  ['paramgenerator',['ParamGenerator',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t1_20_3e',['ParamGenerator&lt; T1 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t10_20_3e',['ParamGenerator&lt; T10 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t2_20_3e',['ParamGenerator&lt; T2 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t3_20_3e',['ParamGenerator&lt; T3 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t4_20_3e',['ParamGenerator&lt; T4 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t5_20_3e',['ParamGenerator&lt; T5 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t6_20_3e',['ParamGenerator&lt; T6 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t7_20_3e',['ParamGenerator&lt; T7 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t8_20_3e',['ParamGenerator&lt; T8 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgenerator_3c_20t9_20_3e',['ParamGenerator&lt; T9 &gt;',['../classtesting_1_1internal_1_1ParamGenerator.html',1,'testing::internal']]],
  ['paramgeneratorinterface',['ParamGeneratorInterface',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_2c_20t4_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3, T4 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3, T4, T5 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3, T4, T5, T6 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3, T4, T5, T6, T7 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_2c_20t8_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3, T4, T5, T6, T7, T8 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_2c_20t8_2c_20t9_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3, T4, T5, T6, T7, T8, T9 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20_3a_3astd_3a_3atr1_3a_3atuple_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_2c_20t8_2c_20t9_2c_20t10_20_3e_20_3e',['ParamGeneratorInterface&lt; ::std::tr1::tuple&lt; T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 &gt; &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20std_3a_3atr1_3a_3atuple_20_3e',['ParamGeneratorInterface&lt; std::tr1::tuple &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20t_20_3e',['ParamGeneratorInterface&lt; T &gt;',['../classtesting_1_1internal_1_1ParamGeneratorInterface.html',1,'testing::internal']]],
  ['paramiterator',['ParamIterator',['../classtesting_1_1internal_1_1ParamIterator.html',1,'testing::internal']]],
  ['paramiteratorinterface',['ParamIteratorInterface',['../classtesting_1_1internal_1_1ParamIteratorInterface.html',1,'testing::internal']]],
  ['paramiteratorinterface_3c_20paramtype_20_3e',['ParamIteratorInterface&lt; ParamType &gt;',['../classtesting_1_1internal_1_1ParamIteratorInterface.html',1,'testing::internal']]],
  ['params',['Params',['../structcv_1_1gpu_1_1FGDStatModel_1_1Params.html',1,'cv::gpu::FGDStatModel']]],
  ['parse_5fcontext',['parse_context',['../structparse__context.html',1,'']]],
  ['parseexception',['ParseException',['../classlibconfig_1_1ParseException.html',1,'libconfig']]],
  ['performance_5fmetrics',['performance_metrics',['../structperf_1_1performance__metrics.html',1,'perf']]],
  ['perfskiptestexception',['PerfSkipTestException',['../classperf_1_1TestBase_1_1PerfSkipTestException.html',1,'perf::TestBase']]],
  ['planeportraitprojector',['PlanePortraitProjector',['../structcv_1_1detail_1_1PlanePortraitProjector.html',1,'cv::detail']]],
  ['planeportraitwarper',['PlanePortraitWarper',['../classcv_1_1detail_1_1PlanePortraitWarper.html',1,'cv::detail']]],
  ['planeprojector',['PlaneProjector',['../structcv_1_1detail_1_1PlaneProjector.html',1,'cv::detail']]],
  ['planewarper',['PlaneWarper',['../classcv_1_1detail_1_1PlaneWarper.html',1,'cv::detail']]],
  ['planewarper',['PlaneWarper',['../classcv_1_1PlaneWarper.html',1,'cv']]],
  ['platforminfo',['PlatformInfo',['../structcv_1_1ocl_1_1PlatformInfo.html',1,'cv::ocl']]],
  ['plus',['plus',['../structcv_1_1gpu_1_1device_1_1plus.html',1,'cv::gpu::device']]],
  ['pointertraits',['PointerTraits',['../structcv_1_1gpu_1_1device_1_1type__traits__detail_1_1PointerTraits.html',1,'cv::gpu::device::type_traits_detail']]],
  ['pointertraits_3c_20u_20_2a_20_3e',['PointerTraits&lt; U * &gt;',['../structcv_1_1gpu_1_1device_1_1type__traits__detail_1_1PointerTraits_3_01U_01_5_01_4.html',1,'cv::gpu::device::type_traits_detail']]],
  ['pointertraits_3c_20u_20_2a_26_20_3e',['PointerTraits&lt; U *&amp; &gt;',['../structcv_1_1gpu_1_1device_1_1type__traits__detail_1_1PointerTraits_3_01U_01_5_6_01_4.html',1,'cv::gpu::device::type_traits_detail']]],
  ['pointfilter',['PointFilter',['../structcv_1_1gpu_1_1device_1_1PointFilter.html',1,'cv::gpu::device']]],
  ['pooledallocator',['PooledAllocator',['../classcvflann_1_1PooledAllocator.html',1,'cvflann']]],
  ['programsource',['ProgramSource',['../structcv_1_1ocl_1_1ProgramSource.html',1,'cv::ocl']]],
  ['project1st',['project1st',['../structcv_1_1gpu_1_1device_1_1project1st.html',1,'cv::gpu::device']]],
  ['project2nd',['project2nd',['../structcv_1_1gpu_1_1device_1_1project2nd.html',1,'cv::gpu::device']]],
  ['projectorbase',['ProjectorBase',['../structcv_1_1detail_1_1ProjectorBase.html',1,'cv::detail']]],
  ['pyrlkoptflowestimatorbase',['PyrLkOptFlowEstimatorBase',['../classcv_1_1videostab_1_1PyrLkOptFlowEstimatorBase.html',1,'cv::videostab']]],
  ['pyrlkopticalflow',['PyrLKOpticalFlow',['../classcv_1_1ocl_1_1PyrLKOpticalFlow.html',1,'cv::ocl']]],
  ['pyrlkopticalflow',['PyrLKOpticalFlow',['../classcv_1_1gpu_1_1PyrLKOpticalFlow.html',1,'cv::gpu']]],
  ['pyrlkrobustmotionestimator',['PyrLkRobustMotionEstimator',['../classcv_1_1videostab_1_1PyrLkRobustMotionEstimator.html',1,'cv::videostab']]]
];
